### ISSUE TITLE
WTF Command does not get WTF properly

### ISSUE THREAD

**Issue by DalekCraft2** [Jacobw0/OMORI-Console-Plus#1]
I am using this with OMOCEP 3.7.1, and the `/wtf` command by itself prints "WTF level is at undefined". It should be at 8, according to `/variable WTF`.

**Comment by GlitchyZorua** [comment]
I'll fix it later, I have to do school rn, my apologies

**Comment by GlitchyZorua** [comment]
Fixed! Will be added in the next update!
