### ISSUE TITLE
Add file to check the current background music being played

### ISSUE THREAD

**Issue by Lusbert** [Jacobw0/OMORI-Console-Plus#2]
Being able to check what BGM is currently playing would be nice.
i tested it for bugs and it doesn't have any(probably because it doesn't do anything important)
GitHub doesn't let me upload the javascript so just remove the .txt
[BGMnow.js.txt](https://github.com/GlitchyZorua/OMORI-Console-Plus/files/11787819/BGMnow.js.txt)

**Comment by Lusbert** [comment]
Update for not giving an error when there is no background music being played.
[BGMnow.js.txt](https://github.com/GlitchyZorua/OMORI-Console-Plus/files/11796466/BGMnow.js.txt)

**Comment by GlitchyZorua** [comment]
ok, i'll add this. thanks for your contribution.
