### ISSUE TITLE
Add file to check the current map the player is in

### ISSUE THREAD

**Issue by Lusbert** [Jacobw0/OMORI-Console-Plus#3]
Another file for checking the name of the current map the player is in
[MapName.js.txt](https://github.com/GlitchyZorua/OMORI-Console-Plus/files/12021763/MapName.js.txt)
checked for "bugs" and doesn't crash the game when the player isn't in a map

**Comment by GlitchyZorua** [comment]
will be added

**Comment by GlitchyZorua** [comment]
ok this has been implemented.

**Comment by DalekCraft2** [comment]
I feel I should point out that this functionality [has been added to the base console mod already](https://github.com/surrealegg/debug-console/commit/63b0be4d364b0db95e4b76237c2803268c8f84f7).

**Comment by GlitchyZorua** [comment]
Okay yeah, noted
